name: plant_village
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker: ^1.1.2
  image: ^4.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/plant_model.tflite
    - assets/labels.txt
